-- KING VANDYZ production migration
-- Run in Supabase SQL Editor. Existing tables/functions are preserved where possible.

create extension if not exists pgcrypto;

alter table if exists public.profiles add column if not exists free_credits integer not null default 100;
alter table if exists public.profiles add column if not exists purchased_credits integer not null default 0;
alter table if exists public.profiles add column if not exists free_reset_at timestamptz;
alter table if exists public.profiles add column if not exists vip_until timestamptz;
alter table if exists public.profiles add column if not exists joined_at timestamptz not null default now();
alter table if exists public.profiles add column if not exists last_active timestamptz not null default now();
alter table if exists public.profiles add column if not exists tool_uses bigint not null default 0;
alter table if exists public.profiles add column if not exists disabled boolean not null default false;
alter table if exists public.profiles add column if not exists role text not null default 'user';

create table if not exists public.site_settings (
 id boolean primary key default true,
 site_name text not null default 'KING VANDYZ', site_tagline text not null default 'YOUR TOOLS. YOUR POWER.', site_description text not null default '',
 logo_url text, banner_video_url text, banner_image_url text default '/banner.jpg', banner_position text not null default 'center', banner_overlay numeric not null default 0.22, banner_alt text not null default 'KING VANDYZ banner', theme_config jsonb not null default '{}'::jsonb, whatsapp_number text not null default '083818597706', footer_text text,
 default_theme text not null default 'brutal', maintenance_enabled boolean not null default false,
 maintenance_title text not null default 'SYSTEM MAINTENANCE', maintenance_message text not null default 'KING VANDYZ sedang melakukan maintenance.', maintenance_end timestamptz,
 updated_at timestamptz not null default now(), updated_by uuid references auth.users(id)
);
insert into public.site_settings(id,banner_image_url,banner_position,banner_overlay,banner_alt,theme_config) values(true,'/banner.jpg','center',0.22,'KING VANDYZ banner',jsonb_build_object(
 'glass',jsonb_build_object('bg','#07080d','surface','#0d1018','surface2','#121722','text','#f6f7fb','muted','#8d96aa','border','#2a3040','primary','#66e6ff','secondary','#c58cff','accent','#66e6ff'),
 'brutal',jsonb_build_object('bg','#FFFDF5','surface','#FFFFFF','surface2','#FFFFFF','text','#090909','muted','#4a4640','border','#090909','primary','#4D7CFF','secondary','#A77BFF','accent','#FFD23F'),
 'city',jsonb_build_object('bg','#08111b','surface','#0d1925','surface2','#122333','text','#eff7ff','muted','#8ba0b6','border','#2a4257','primary','#7bd9ff','secondary','#78a8ff','accent','#7bd9ff'),
 'comic',jsonb_build_object('bg','#fff6dc','surface','#FFFFFF','surface2','#FFFFFF','text','#17120d','muted','#6e5e4c','border','#17120d','primary','#1769ff','secondary','#ff3d8d','accent','#ffe05c')
 )) on conflict(id) do nothing;

create table if not exists public.homepage_config (
 id boolean primary key default true,
 hero_title text not null default 'YOUR TOOLS. YOUR POWER.', hero_subtitle text not null default 'Premium tools, APIs, and utilities in one workspace.', hero_cta text not null default 'EXPLORE TOOLS',
 stats_visible boolean not null default true, popular_visible boolean not null default true, about_visible boolean not null default true, pricing_visible boolean not null default true, information_visible boolean not null default true,
 updated_at timestamptz not null default now(), updated_by uuid references auth.users(id)
);
insert into public.homepage_config(id) values(true) on conflict(id) do nothing;

create table if not exists public.tool_configs (
 id bigint generated by default as identity primary key, tool_id text unique not null, display_name text not null, description text, category text, icon text,
 enabled boolean not null default true, maintenance boolean not null default false, popular boolean not null default false, featured boolean not null default false,
 sort_order integer not null default 0, credits_cost integer not null default 10, updated_at timestamptz not null default now(), updated_by uuid references auth.users(id)
);

create table if not exists public.announcements (
 id bigint generated by default as identity primary key, title text not null, content text not null, type text not null default 'INFO', active boolean not null default true,
 priority integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id)
);

create table if not exists public.pricing (
 id text primary key, title text not null, normal_price integer not null, promo_price integer not null, promo_active boolean not null default false,
 credits integer not null default 0, vip_days integer not null default 0, description text, sort_order integer not null default 0, active boolean not null default true,
 updated_at timestamptz not null default now(), updated_by uuid references auth.users(id)
);
insert into public.pricing(id,title,normal_price,promo_price,promo_active,credits,vip_days,description,sort_order) values
('credits-500','500 Credits',20000,10000,true,500,0,'Wallet credits, never expire.',1),
('credits-1000','1000 Credits',40000,15000,true,1000,0,'Larger credit pack.',2),
('vip-1m','VIP 1 Month',15000,15000,false,0,30,'Unlimited tool usage while active.',3)
on conflict(id) do nothing;

create table if not exists public.admin_activity_logs (
 id bigint generated by default as identity primary key, admin_id uuid references auth.users(id), admin_username text, action text not null, target_type text, target_id text, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create table if not exists public.orders (
 id text primary key default ('KV-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))), user_id uuid references auth.users(id) on delete cascade,
 username text not null, product text not null, price integer not null, credits integer not null default 0, vip_days integer not null default 0,
 status text not null default 'PENDING', created_at timestamptz not null default now(), completed_at timestamptz
);

create table if not exists public.tool_usage (
 id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete cascade, tool_id text not null, tool_name text, credits_cost integer not null default 0, created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles p where p.id=auth.uid() and lower(p.role)='admin' and coalesce(p.disabled,false)=false);
$$;


create or replace function public.sync_access_state() returns void language plpgsql security definer set search_path=public as $$
begin
 update public.profiles set role='user' where id=auth.uid() and lower(role)='vip' and (vip_until is null or vip_until<=now());
 update public.profiles set free_credits=100, free_reset_at=null where id=auth.uid() and free_credits=0 and free_reset_at is not null and free_reset_at<=now();
end; $$;

create or replace function public.touch_presence() returns void language plpgsql security definer set search_path=public as $$
begin update public.profiles set last_active=now() where id=auth.uid(); end; $$;

create or replace function public.consume_tool_v2(p_tool_id text, p_cost integer default 10) returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.profiles%rowtype; c integer; f integer; r integer;
begin
 select * into p from public.profiles where id=auth.uid() for update;
 if p.id is null then raise exception 'SESSION_EXPIRED'; end if;
 if p.disabled then raise exception 'ACCOUNT_DISABLED'; end if;
 if lower(p.role)='vip' and (p.vip_until is null or p.vip_until<=now()) then p.role:='user'; update public.profiles set role='user' where id=p.id; end if;
 if lower(p.role)='admin' then c:=0;
 elsif p.vip_until is not null and p.vip_until>now() then c:=0;
 else
   if p.free_credits=0 and p.free_reset_at is not null and p.free_reset_at<=now() then p.free_credits:=100; p.free_reset_at:=null; end if;
   if p.free_credits >= p_cost then f:=p_cost; r:=0; elsif p.free_credits>0 then f:=p.free_credits; r:=p_cost-p.free_credits; else f:=0; r:=p_cost; end if;
   if p.purchased_credits < r then raise exception 'INSUFFICIENT_CREDITS'; end if;
   p.free_credits:=p.free_credits-f; p.purchased_credits:=p.purchased_credits-r;
   if p.free_credits=0 and p.free_reset_at is null then p.free_reset_at:=now()+interval '1 hour'; end if;
   c:=p_cost;
 end if;
 update public.profiles set free_credits=p.free_credits,purchased_credits=p.purchased_credits,free_reset_at=p.free_reset_at,tool_uses=coalesce(p.tool_uses,0)+1,last_active=now() where id=p.id;
 insert into public.tool_usage(user_id,tool_id,credits_cost) values(auth.uid(),p_tool_id,c);
 return jsonb_build_object('ok',true,'credits_cost',c,'free_credits',p.free_credits,'purchased_credits',p.purchased_credits,'vip_until',p.vip_until,'role',p.role);
exception when others then
 if sqlerrm in ('INSUFFICIENT_CREDITS','ACCOUNT_DISABLED','SESSION_EXPIRED') then raise; else raise; end if;
end; $$;

create or replace function public.public_stats() returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('total_users',(select count(*) from profiles where coalesce(disabled,false)=false),'online_users',(select count(*) from profiles where coalesce(disabled,false)=false and last_active>now()-interval '3 minutes'));
$$;
create or replace function public.admin_stats() returns jsonb language sql stable security definer set search_path=public as $$
 select case when public.is_admin() then jsonb_build_object(
 'total_users',(select count(*) from profiles),
 'active_users',(select count(*) from profiles where coalesce(disabled,false)=false),
 'online_users',(select count(*) from profiles where coalesce(disabled,false)=false and last_active>now()-interval '3 minutes'),
 'free_users',(select count(*) from profiles where lower(role)='user'),
 'vip_users',(select count(*) from profiles where lower(role)='vip' and vip_until>now()),
 'admin_users',(select count(*) from profiles where lower(role)='admin'),
 'pending_orders',(select count(*) from orders where status='PENDING'),
 'completed_orders',(select count(*) from orders where status='COMPLETED'),
 'total_tool_uses',(select count(*) from tool_usage),
 'credits_sold',(select coalesce(sum(credits),0) from orders where status='COMPLETED'),
 'vip_sold',(select coalesce(sum(vip_days),0) from orders where status='COMPLETED')
 ) else '{}'::jsonb end;
$$;

create or replace function public.create_order(p_product text,p_price integer,p_credits integer default 0,p_vip_days integer default 0) returns public.orders language plpgsql security definer set search_path=public as $$
declare u public.profiles%rowtype; o public.orders;
begin select * into u from profiles where id=auth.uid(); if u.id is null then raise exception 'SESSION_EXPIRED'; end if;
insert into orders(user_id,username,product,price,credits,vip_days) values(auth.uid(),u.username,p_product,p_price,p_credits,p_vip_days) returning * into o; return o; end; $$;

create or replace function public.complete_order(p_order_id text) returns public.orders language plpgsql security definer set search_path=public as $$
declare o public.orders; v public.profiles%rowtype;
begin
 if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
 select * into o from orders where id=p_order_id for update;
 if o.id is null then raise exception 'ORDER_NOT_FOUND'; end if;
 if o.status='COMPLETED' then return o; end if;
 if o.status<>'PENDING' then raise exception 'ORDER_NOT_PENDING'; end if;
 select * into v from profiles where id=o.user_id for update;
 update profiles set purchased_credits=coalesce(purchased_credits,0)+o.credits, vip_until=case when o.vip_days>0 then greatest(coalesce(vip_until,now()),now())+make_interval(days=>o.vip_days) else vip_until end, role=case when o.vip_days>0 then 'vip' else role end where id=o.user_id;
 update orders set status='COMPLETED',completed_at=now() where id=o.id returning * into o;
 insert into admin_activity_logs(admin_id,admin_username,action,target_type,target_id,details) select auth.uid(),username,'completed order','order',o.id,jsonb_build_object('credits',o.credits,'vip_days',o.vip_days) from profiles where id=auth.uid();
 return o;
end; $$;

create or replace function public.adjust_purchased_credits(p_user_id uuid,p_delta integer) returns public.profiles language plpgsql security definer set search_path=public as $$
declare p public.profiles;
begin if not public.is_admin() then raise exception 'FORBIDDEN'; end if; update profiles set purchased_credits=greatest(0,coalesce(purchased_credits,0)+p_delta) where id=p_user_id returning * into p; return p; end; $$;
create or replace function public.grant_vip(p_user_id uuid,p_days integer default 30) returns public.profiles language plpgsql security definer set search_path=public as $$
declare p public.profiles;
begin if not public.is_admin() then raise exception 'FORBIDDEN'; end if; update profiles set vip_until=greatest(coalesce(vip_until,now()),now())+make_interval(days=>p_days),role=case when lower(role)<>'admin' then 'vip' else role end where id=p_user_id returning * into p; return p; end; $$;
create or replace function public.revoke_vip(p_user_id uuid) returns public.profiles language plpgsql security definer set search_path=public as $$
declare p public.profiles;
begin if not public.is_admin() then raise exception 'FORBIDDEN'; end if; update profiles set vip_until=null,role=case when lower(role)='vip' then 'user' else role end where id=p_user_id returning * into p; return p; end; $$;

alter table public.profiles enable row level security; alter table public.orders enable row level security; alter table public.tool_usage enable row level security;
alter table public.site_settings enable row level security; alter table public.homepage_config enable row level security; alter table public.tool_configs enable row level security; alter table public.announcements enable row level security; alter table public.pricing enable row level security; alter table public.admin_activity_logs enable row level security;

do $$ begin
 create policy profiles_self_or_admin_select on public.profiles for select using (id=auth.uid() or public.is_admin());
exception when duplicate_object then null; end $$;
do $$ begin create policy orders_self_or_admin_select on public.orders for select using (user_id=auth.uid() or public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy tool_usage_self_or_admin_select on public.tool_usage for select using (user_id=auth.uid() or public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy site_settings_public_select on public.site_settings for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy homepage_public_select on public.homepage_config for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy tool_configs_public_select on public.tool_configs for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy announcements_public_select on public.announcements for select using (active=true or public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy pricing_public_select on public.pricing for select using (active=true or public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy admin_logs_admin_select on public.admin_activity_logs for select using (public.is_admin()); exception when duplicate_object then null; end $$;

-- Admin writes are exposed only through the REST layer when RLS confirms admin; for sensitive mutations prefer the security-definer RPCs above.
do $$ begin create policy site_settings_admin_write on public.site_settings for all using(public.is_admin()) with check(public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy homepage_admin_write on public.homepage_config for all using(public.is_admin()) with check(public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy tool_configs_admin_write on public.tool_configs for all using(public.is_admin()) with check(public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy announcements_admin_write on public.announcements for all using(public.is_admin()) with check(public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy pricing_admin_write on public.pricing for all using(public.is_admin()) with check(public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy admin_logs_admin_write on public.admin_activity_logs for insert with check(public.is_admin()); exception when duplicate_object then null; end $$;

-- New auth users get a profile. If an existing handle_new_user() already exists, keep it; otherwise this trigger provides the profile row.
create or replace function public.handle_new_user_vandyz() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,username,role,free_credits,purchased_credits,joined_at,last_active) values(new.id,lower(coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))),'user',100,0,now(),now()) on conflict(id) do update set username=excluded.username; return new; end; $$;
drop trigger if exists on_auth_user_created_vandyz on auth.users;
create trigger on_auth_user_created_vandyz after insert on auth.users for each row execute procedure public.handle_new_user_vandyz();
do $$ begin create policy profiles_admin_write on public.profiles for update using(public.is_admin()) with check(public.is_admin()); exception when duplicate_object then null; end $$;
do $$ begin create policy orders_admin_write on public.orders for update using(public.is_admin()) with check(public.is_admin()); exception when duplicate_object then null; end $$;
