import React from 'react';
import {Activity,Boxes,CheckCircle2,Clock3,Database,Edit3,LayoutDashboard,Megaphone,RefreshCw,Settings,ShieldCheck,ShoppingBag,SlidersHorizontal,ToggleLeft,Users,Wrench,Palette,Video,Wallet,Infinity} from 'lucide-react';
import {getAdminStats,listRows,mutate,upsertToolConfigs,adminRpc,rejectOrder,setUserDisabled,setUserRole} from '../services/platform';
import {uploadToStorage} from '../services/api';


const THEME_DEFAULTS={
 glass:{bg:'#07080d',surface:'#0d1018',surface2:'#121722',text:'#f6f7fb',muted:'#8d96aa',border:'#2a3040',primary:'#66e6ff',secondary:'#c58cff',accent:'#ff2bd6',highlight:'#66e6ff',shadow:'#000000'},
 brutal:{bg:'#FFFDF5',surface:'#FFFFFF',surface2:'#FFFFFF',text:'#090909',muted:'#4a4640',border:'#090909',primary:'#4D7CFF',secondary:'#A77BFF',accent:'#FF4D5A',highlight:'#FFD23F',shadow:'#090909'},
 city:{bg:'#08111b',surface:'#0d1925',surface2:'#122333',text:'#eff7ff',muted:'#8ba0b6',border:'#2a4257',primary:'#7bd9ff',secondary:'#78a8ff',accent:'#36e1c1',highlight:'#ffcc66',shadow:'#02060b'},
 comic:{bg:'#fff6dc',surface:'#FFFFFF',surface2:'#FFFFFF',text:'#17120d',muted:'#6e5e4c',border:'#17120d',primary:'#1769ff',secondary:'#ff3d8d',accent:'#ffe05c',highlight:'#58d68d',shadow:'#17120d'},
 paper:{bg:'#f5edda',surface:'#fffdf4',surface2:'#f1e7cc',text:'#30261d',muted:'#776957',border:'#4a3828',primary:'#6b4f35',secondary:'#9a7652',accent:'#c65d3a',highlight:'#e6c85c',shadow:'#4a3828'},
 arcade:{bg:'#09051a',surface:'#130b2d',surface2:'#1d1040',text:'#f8f4ff',muted:'#b8a9d9',border:'#6e4cff',primary:'#00e5ff',secondary:'#a66cff',accent:'#ff3cac',highlight:'#ffe45e',shadow:'#05020d'},
 drawing:{bg:'#f8f4ea',surface:'#fffdf7',surface2:'#f2ead8',text:'#2b241e',muted:'#766b5f',border:'#3b3027',primary:'#3157d5',secondary:'#9b59b6',accent:'#ef6b4f',highlight:'#f4c95d',shadow:'#3b3027'}
};
const THEME_LABELS={glass:'Glassmorphism',brutal:'Neo Brutalism',city:'Modern City',comic:'Comic Style',paper:'Paper & Handwriting',arcade:'Retro Arcade',drawing:'Drawing Studio'};
function themeConfigWithDefaults(value){const raw=value&&typeof value==='object'?value:{};return Object.fromEntries(Object.keys(THEME_DEFAULTS).map(id=>[id,{...THEME_DEFAULTS[id],...(raw[id]||{})}]));}
async function uploadImage(file){return uploadToStorage(file,'banners');}

const tabs=[['overview','Overview',LayoutDashboard],['users','Users',Users],['orders','Orders',ShoppingBag],['tools','Tools',Boxes],['pricing','Pricing',Wallet],['homepage','Homepage',SlidersHorizontal],['announcements','Announcements',Megaphone],['channel','Channel Promo',Megaphone],['banner','Banner',Video],['themes','Themes',Palette],['maintenance','Maintenance',Wrench],['analytics','Analytics',Activity],['logs','Activity Log',Database],['settings','Site Settings',Settings]];
function Stat({label,value,icon:Icon}){return <div className="admin-stat"><Icon size={18}/><small>{label}</small><strong>{value??'—'}</strong></div>}
function SaveButton({onClick}){return <button className="btn primary small" onClick={onClick}><CheckCircle2 size={14}/> SAVE</button>}
function Field({label,value,onChange,type='text'}){return <label className="cms-field"><span>{label}</span>{type==='textarea'?<textarea value={value??''} onChange={e=>onChange(e.target.value)}/>:type==='checkbox'?<input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
function ColorField({label,value,onChange}){return <label className="cms-field color-field"><span>{label}</span><div><input type="color" value={value||'#000000'} onChange={e=>onChange(e.target.value)}/><code>{value||'#000000'}</code></div></label>}
export default function Admin({profile,catalogTools=[],onExit}){
 const [tab,setTab]=React.useState('overview'),[stats,setStats]=React.useState({}),[users,setUsers]=React.useState([]),[orders,setOrders]=React.useState([]),[tools,setTools]=React.useState([]),[pricing,setPricing]=React.useState([]),[settings,setSettings]=React.useState(null),[home,setHome]=React.useState(null),[ann,setAnn]=React.useState([]),[logs,setLogs]=React.useState([]),[themeDraft,setThemeDraft]=React.useState(themeConfigWithDefaults()),[bannerUploading,setBannerUploading]=React.useState(false),[loading,setLoading]=React.useState(true),[notice,setNotice]=React.useState(''),[toolSearch,setToolSearch]=React.useState('');
 const load=React.useCallback(async()=>{setLoading(true);try{const s=await getAdminStats();setStats(s||{});const [u,o,t,p,ss,h,a,l]=await Promise.all([listRows('profiles','?select=id,username,role,free_credits,purchased_credits,free_reset_at,vip_until,joined_at,last_active,tool_uses,disabled&order=joined_at.desc'),listRows('orders','?select=*&order=created_at.desc'),listRows('tool_configs','?select=*&order=sort_order.asc'),listRows('pricing','?select=*&order=sort_order.asc'),listRows('site_settings','?select=*&limit=1'),listRows('homepage_config','?select=*&limit=1'),listRows('announcements','?select=*&order=priority.desc,created_at.desc'),listRows('admin_activity_logs','?select=*&order=created_at.desc&limit=100')]);setUsers(u||[]);setOrders(o||[]);
 const dbTools=Array.isArray(t)?t:[];
 const dbMap=new Map(dbTools.map(x=>[x.tool_id,x]));
 const merged=(catalogTools||[]).map((ct,i)=>{const x=dbMap.get(ct.id);return x||{id:`catalog-${ct.id}`,tool_id:ct.id,display_name:ct.name,description:ct.description,category:ct.category,enabled:true,maintenance:false,popular:false,featured:i<3,sort_order:i,credits_cost:10,_catalogOnly:true};});
 const legacy=dbTools.filter(x=>!(catalogTools||[]).some(ct=>ct.id===x.tool_id));
 setTools([...merged,...legacy]);setPricing(p||[]);const site=ss?.[0]||null;setSettings(site);setThemeDraft(themeConfigWithDefaults(site?.theme_config));setHome(h?.[0]||null);setAnn(a||[]);setLogs(l||[])}catch(e){setNotice(e?.message||'Gagal memuat CMS.')}finally{setLoading(false)}},[catalogTools]);
 React.useEffect(()=>{load()},[load]);
 const save=async(fn,msg='Saved')=>{try{await fn();setNotice(msg);await load()}catch(e){setNotice(e?.message||'Save gagal')}};
 const complete=async id=>save(()=>adminRpc('complete_order',{p_order_id:id}),'Order completed.');
 const adjust=async(u,delta)=>save(()=>adminRpc('adjust_purchased_credits',{p_user_id:u.id,p_delta:Number(delta)}),'Credits updated.');
 const vip=async(u)=>save(()=>adminRpc('grant_vip',{p_user_id:u.id,p_days:30}),'VIP granted.');
 const revoke=async(u)=>save(()=>adminRpc('revoke_vip',{p_user_id:u.id}),'VIP revoked.');
 const toggleUser=async u=>save(()=>setUserDisabled(u.id,!u.disabled),'User status updated.');
 const changeRole=async(u,role)=>{if(u.id===profile?.id&&role!=='ADMIN'){setNotice('Jangan turunkan role akun admin yang sedang dipakai.');return}await save(()=>setUserRole(u.id,role),'Role updated.');};
 const updateRow=(set,id,key,val)=>set(rows=>rows.map(x=>x.id===id?{...x,[key]:val}:x));
 const applyThemeTokens=(id,cfg)=>{document.documentElement.dataset.theme=id;const map={bg:'--theme-bg',surface:'--theme-surface',surface2:'--theme-surface2',text:'--theme-text',muted:'--theme-muted',border:'--theme-border',primary:'--theme-primary',secondary:'--theme-secondary',accent:'--theme-accent',highlight:'--theme-highlight',shadow:'--theme-shadow'};Object.entries(map).forEach(([k,v])=>document.documentElement.style.setProperty(v,cfg[k]||''));const legacy={bg:'--bg',surface:'--surface',surface2:'--surface-2',text:'--text',muted:'--muted',border:'--line',primary:'--cyan',secondary:'--purple',accent:'--pink',highlight:'--yellow',shadow:'--shadow'};Object.entries(legacy).forEach(([k,v])=>document.documentElement.style.setProperty(v,cfg[k]||''));};
 const previewTheme=(forcedId)=>{const id=forcedId||settings?.default_theme||'brutal';const cfg={...(THEME_DEFAULTS[id]||{}),...(themeDraft[id]||{})};try{localStorage.setItem('king-vandyz-theme-v2',id)}catch{};applyThemeTokens(id,cfg);window.dispatchEvent(new Event('kv-theme-change'));};
 if(loading&&!settings)return <div className="admin-page"><div className="empty">Loading KING VANDYZ CONTROL CENTER…</div></div>;
 return <div className="admin-page"><div className="admin-top"><div><small>DATABASE-BACKED CMS</small><h1>KING VANDYZ <em>CONTROL CENTER</em></h1><p>Content, configuration, users, orders, tools, pricing, maintenance, and analytics.</p></div><div className="admin-actions"><button className="icon-btn" onClick={load}><RefreshCw size={17}/></button><button className="btn ghost" onClick={onExit}>Exit</button></div></div>{notice&&<div className="cms-notice">{notice}</div>}<div className="admin-shell"><aside className="admin-nav">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</aside><main className="admin-content">{tab==='overview'&&<><div className="admin-grid"><Stat icon={Users} label="TOTAL USERS" value={stats.total_users}/><Stat icon={Activity} label="ONLINE" value={stats.online_users}/><Stat icon={Wallet} label="CREDITS SOLD" value={stats.credits_sold}/><Stat icon={ShoppingBag} label="PENDING ORDERS" value={stats.pending_orders}/><Stat icon={Infinity} label="VIP USERS" value={stats.vip_users}/><Stat icon={Boxes} label="TOOL USES" value={stats.total_tool_uses}/></div><section className="cms-panel"><h2>System</h2><p>Admin/VVIP permissions are database-backed through <code>is_admin()</code>. Credits/VIP mutations use security-definer RPCs.</p><div className="status-row"><span>Admin</span><b>VERIFIED</b><ShieldCheck size={16}/></div><div className="status-row"><span>Maintenance</span><b>{settings?.maintenance_enabled?'ON':'OFF'}</b><Wrench size={16}/></div></section></>}
 {tab==='users'&&<section className="cms-panel"><div className="panel-head"><h2>Users</h2><span>{users.length} accounts</span></div><div className="cms-table">{users.map(u=><div className="cms-row" key={u.id}><div><b>{u.username}</b><span>{u.role?.toUpperCase()} · {u.disabled?'DISABLED':'ACTIVE'}</span></div><div><span>Free {u.free_credits}</span><span>Purchased {u.purchased_credits}</span></div><div><span>VIP {u.vip_until?new Date(u.vip_until).toLocaleDateString('id-ID'):'—'}</span><span>Uses {u.tool_uses||0}</span></div><div className="row-actions"><select value={String(u.role||'user').toUpperCase()} onChange={e=>changeRole(u,e.target.value)}><option value="USER">USER</option><option value="VIP">VIP</option><option value="ADMIN">ADMIN</option></select><button onClick={()=>adjust(u,100)}>+100</button><button onClick={()=>adjust(u,-100)}>-100</button><button onClick={()=>vip(u)}>VIP 30d</button><button onClick={()=>revoke(u)}>Revoke</button><button onClick={()=>toggleUser(u)}>{u.disabled?'Enable':'Disable'}</button></div></div>)}</div></section>}
 {tab==='orders'&&<section className="cms-panel"><h2>Orders</h2><div className="cms-table">{orders.map(o=><div className="cms-row" key={o.id}><div><b>{o.id}</b><span>{o.username}</span></div><div><span>{o.product}</span><span>Rp{Number(o.price).toLocaleString('id-ID')}</span></div><div><span>{o.credits} credits</span><span>{o.vip_days} VIP days</span></div><div className="row-actions">{o.status==='PENDING'?<><button onClick={()=>complete(o.id)}>SUDAH BAYAR</button><button onClick={()=>save(()=>rejectOrder(o.id),'Order rejected.')}>REJECT</button></>:<em className={`order-status ${o.status.toLowerCase()}`}>{o.status}</em>}</div></div>)}</div></section>}
 {tab==='tools'&&(()=>{const visibleTools=tools.filter(t=>{const q=toolSearch.trim().toLowerCase();return !q||`${t.display_name} ${t.tool_id} ${t.category}`.toLowerCase().includes(q)});const syncCatalog=async()=>save(async()=>{const dbMap=new Map(tools.filter(x=>!x._catalogOnly).map(x=>[x.tool_id,x]));const rows=(catalogTools||[]).map((ct,i)=>{const old=dbMap.get(ct.id);return {tool_id:ct.id,display_name:ct.name,description:ct.description,category:ct.category,enabled:old?.enabled!==false,maintenance:Boolean(old?.maintenance),popular:Boolean(old?.popular),featured:old?.featured??(i<3),sort_order:old?.sort_order??i,credits_cost:Number(old?.credits_cost??10)}});await upsertToolConfigs(rows)},`${catalogTools.length} tools berhasil disinkronkan ke CMS.`);const toggleHide=async t=>{setTools(rows=>rows.map(x=>x.id===t.id?{...x,enabled:!x.enabled}:x));setNotice(t.enabled?'Tool disembunyikan di draft. Tekan SAVE ALL untuk menerapkan.':'Tool ditampilkan di draft. Tekan SAVE ALL untuk menerapkan.')};const saveAllTools=async()=>save(async()=>{const rows=tools.map((t,i)=>({tool_id:t.tool_id,display_name:t.display_name,description:t.description,category:t.category,enabled:t.enabled!==false,maintenance:Boolean(t.maintenance),popular:Boolean(t.popular),featured:Boolean(t.featured),sort_order:Number(t.sort_order??i),credits_cost:Number(t.credits_cost??10)}));await upsertToolConfigs(rows)},'Semua pengaturan tools tersimpan ke Supabase.');return <section className="cms-panel"><div className="panel-head tools-admin-head"><div><h2>Tool Management</h2><span>{tools.length} tools · {catalogTools.length} live catalog · perubahan disimpan permanen</span></div><div className="tool-admin-actions"><input className="tool-admin-search" placeholder="Cari tool / endpoint…" value={toolSearch} onChange={e=>setToolSearch(e.target.value)}/><button className="btn ghost small" onClick={syncCatalog}><RefreshCw size={14}/> SYNC {catalogTools.length}+ TOOLS</button><button className="btn primary small" onClick={saveAllTools}><CheckCircle2 size={14}/> SAVE ALL CHANGES</button></div></div><div className="cms-table">{visibleTools.map(t=><div className={`cms-row tool-cms ${t.enabled?'':'tool-hidden'}`} key={t.id}><div><b>{t.display_name}</b><span>{t.tool_id} · {t.category||'other'} {t._catalogOnly&&'· NOT SYNCED'}</span></div><Field label="Cost" value={t.credits_cost} onChange={v=>updateRow(setTools,t.id,'credits_cost',Number(v))} type="number"/><Field label="Visible" value={t.enabled} onChange={v=>updateRow(setTools,t.id,'enabled',v)} type="checkbox"/><Field label="Maintenance" value={t.maintenance} onChange={v=>updateRow(setTools,t.id,'maintenance',v)} type="checkbox"/><Field label="Popular" value={t.popular} onChange={v=>updateRow(setTools,t.id,'popular',v)} type="checkbox"/><button className={`tool-hide-btn ${t.enabled?'':'is-hidden'}`} onClick={()=>toggleHide(t)}>{t.enabled?'HIDE TOOL':'SHOW TOOL'}</button></div>)}</div></section>})()}
 {tab==='pricing'&&<section className="cms-panel"><div className="panel-head"><h2>Pricing CMS</h2><button className="btn ghost small" onClick={()=>save(async()=>{for(const p of pricing)await mutate('pricing','PATCH',{title:p.title,normal_price:p.normal_price,promo_price:p.promo_price,promo_active:p.promo_active,credits:p.credits,vip_days:p.vip_days,description:p.description},`?id=eq.${p.id}`)},'Pricing saved.')}>Save pricing</button></div>{pricing.map(p=><div className="cms-editor" key={p.id}><Field label="Title" value={p.title} onChange={v=>updateRow(setPricing,p.id,'title',v)}/><Field label="Normal Price" value={p.normal_price} onChange={v=>updateRow(setPricing,p.id,'normal_price',Number(v))} type="number"/><Field label="Promo Price" value={p.promo_price} onChange={v=>updateRow(setPricing,p.id,'promo_price',Number(v))} type="number"/><Field label="Promo Active" value={p.promo_active} onChange={v=>updateRow(setPricing,p.id,'promo_active',v)} type="checkbox"/><Field label="Credits" value={p.credits} onChange={v=>updateRow(setPricing,p.id,'credits',Number(v))} type="number"/><Field label="VIP Days" value={p.vip_days} onChange={v=>updateRow(setPricing,p.id,'vip_days',Number(v))} type="number"/></div>)}</section>}
 {tab==='homepage'&&<section className="cms-panel"><h2>Homepage CMS</h2>{home&&<><Field label="Hero Title" value={home.hero_title} onChange={v=>setHome({...home,hero_title:v})}/><Field label="Hero Subtitle" value={home.hero_subtitle} onChange={v=>setHome({...home,hero_subtitle:v})}/><Field label="Hero CTA" value={home.hero_cta} onChange={v=>setHome({...home,hero_cta:v})}/><div className="cms-checks"><Field label="Stats" value={home.stats_visible} onChange={v=>setHome({...home,stats_visible:v})} type="checkbox"/><Field label="Popular" value={home.popular_visible} onChange={v=>setHome({...home,popular_visible:v})} type="checkbox"/><Field label="About" value={home.about_visible} onChange={v=>setHome({...home,about_visible:v})} type="checkbox"/><Field label="Pricing" value={home.pricing_visible} onChange={v=>setHome({...home,pricing_visible:v})} type="checkbox"/></div><SaveButton onClick={()=>save(()=>mutate('homepage_config','PATCH',home,'?id=eq.true'),'Homepage saved.')}/></>}</section>}
 {tab==='channel'&&<section className="cms-panel"><h2>WhatsApp Channel Promotion</h2>{settings&&<><Field label="Enable Promotion" value={settings.channel_promo_enabled} onChange={v=>setSettings({...settings,channel_promo_enabled:v})} type="checkbox"/><Field label="Channel Name" value={settings.channel_promo_name||'KING VANDYZ CHANNEL'} onChange={v=>setSettings({...settings,channel_promo_name:v})}/><Field label="Title" value={settings.channel_promo_title||'Stay Updated with KING VANDYZ'} onChange={v=>setSettings({...settings,channel_promo_title:v})}/><Field label="Description" value={settings.channel_promo_description||''} onChange={v=>setSettings({...settings,channel_promo_description:v})} type="textarea"/><Field label="Channel URL" value={settings.channel_promo_url||'https://whatsapp.com/channel/0029VbEFmPM6buMLQgdlie1J'} onChange={v=>setSettings({...settings,channel_promo_url:v})}/><Field label="Button Text" value={settings.channel_promo_button||'JOIN CHANNEL'} onChange={v=>setSettings({...settings,channel_promo_button:v})}/><Field label="Show on Home" value={settings.channel_promo_home} onChange={v=>setSettings({...settings,channel_promo_home:v})} type="checkbox"/><Field label="Show Floating Button" value={settings.channel_promo_floating} onChange={v=>setSettings({...settings,channel_promo_floating:v})} type="checkbox"/><Field label="Dismiss Cooldown (hours)" value={settings.channel_promo_cooldown_hours??24} onChange={v=>setSettings({...settings,channel_promo_cooldown_hours:Math.max(0,Number(v)||0)})} type="number"/><SaveButton onClick={()=>save(()=>mutate('site_settings','PATCH',{channel_promo_enabled:Boolean(settings.channel_promo_enabled),channel_promo_name:settings.channel_promo_name,channel_promo_title:settings.channel_promo_title,channel_promo_description:settings.channel_promo_description,channel_promo_url:settings.channel_promo_url,channel_promo_button:settings.channel_promo_button,channel_promo_home:Boolean(settings.channel_promo_home),channel_promo_floating:Boolean(settings.channel_promo_floating),channel_promo_cooldown_hours:Number(settings.channel_promo_cooldown_hours)||24},'?id=eq.true'),'Channel promotion saved.')}/></>}</section>}
 {tab==='banner'&&<section className="cms-panel"><h2>Banner CMS</h2>{settings&&<><Field label="Banner Image URL" value={settings.banner_image_url||'/banner.jpg'} onChange={v=>setSettings({...settings,banner_image_url:v})}/><label className="cms-field"><span>Upload New Banner</span><input type="file" accept="image/*" disabled={bannerUploading} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setBannerUploading(true);const url=await uploadImage(f);setSettings(x=>({...x,banner_image_url:url}));setNotice('Banner uploaded. Press SAVE to publish it.')}catch(err){setNotice(err?.message||'Upload gagal')}finally{setBannerUploading(false);e.target.value=''}}}/></label><Field label="Object Position" value={settings.banner_position||'center'} onChange={v=>setSettings({...settings,banner_position:v})}/><Field label="Overlay Opacity (0–1)" value={settings.banner_overlay??0.22} onChange={v=>setSettings({...settings,banner_overlay:Math.max(0,Math.min(1,Number(v)||0))})} type="number"/><Field label="Alt Text" value={settings.banner_alt||'KING VANDYZ banner'} onChange={v=>setSettings({...settings,banner_alt:v})}/><div className="banner-admin-preview"><img src={settings.banner_image_url||'/banner.jpg'} alt="Banner preview" style={{objectPosition:settings.banner_position||'center'}}/></div><p className="cms-help">Static 16:9 banner. Upload disimpan permanen di Supabase Storage. URL gambar juga bisa ditempel manual.</p><SaveButton onClick={()=>save(()=>mutate('site_settings','PATCH',{banner_image_url:settings.banner_image_url,banner_position:settings.banner_position,banner_overlay:settings.banner_overlay,banner_alt:settings.banner_alt,banner_video_url:null},'?id=eq.true'),'Banner saved.')}/></>}</section>}
 {tab==='announcements'&&<section className="cms-panel"><div className="panel-head"><h2>Announcements</h2><button className="btn ghost small" onClick={()=>setAnn([{id:`new-${Date.now()}`,title:'New announcement',content:'',type:'INFO',active:true,priority:0},...ann])}>Add</button></div>{ann.map(a=><div className="cms-editor announcement-editor" key={a.id}><Field label="Title" value={a.title} onChange={v=>updateRow(setAnn,a.id,'title',v)}/><Field label="Content" value={a.content} onChange={v=>updateRow(setAnn,a.id,'content',v)} type="textarea"/><Field label="Type" value={a.type} onChange={v=>updateRow(setAnn,a.id,'type',v)}/><Field label="Active" value={a.active} onChange={v=>updateRow(setAnn,a.id,'active',v)} type="checkbox"/><SaveButton onClick={()=>save(()=>a.id.toString().startsWith('new-')?mutate('announcements','POST',{title:a.title,content:a.content,type:a.type,active:a.active,priority:a.priority||0}):mutate('announcements','PATCH',{title:a.title,content:a.content,type:a.type,active:a.active,priority:a.priority},`?id=eq.${a.id}`),'Announcement saved.')}/></div>)}</section>}
 {(tab==='maintenance'||tab==='settings')&&<section className="cms-panel"><h2>{tab==='maintenance'?'Global Maintenance':'Site Settings'}</h2>{settings&&<><Field label="Site Name" value={settings.site_name} onChange={v=>setSettings({...settings,site_name:v})}/><Field label="Tagline" value={settings.site_tagline} onChange={v=>setSettings({...settings,site_tagline:v})}/><Field label="Description" value={settings.site_description} onChange={v=>setSettings({...settings,site_description:v})} type="textarea"/><Field label="WhatsApp Number" value={settings.whatsapp_number} onChange={v=>setSettings({...settings,whatsapp_number:v})}/><Field label="Default Theme" value={settings.default_theme} onChange={v=>setSettings({...settings,default_theme:v})}/><Field label="Maintenance Enabled" value={settings.maintenance_enabled} onChange={v=>setSettings({...settings,maintenance_enabled:v})} type="checkbox"/><Field label="Maintenance Title" value={settings.maintenance_title} onChange={v=>setSettings({...settings,maintenance_title:v})}/><Field label="Maintenance Message" value={settings.maintenance_message} onChange={v=>setSettings({...settings,maintenance_message:v})} type="textarea"/><SaveButton onClick={()=>save(()=>mutate('site_settings','PATCH',{site_name:settings.site_name,site_tagline:settings.site_tagline,site_description:settings.site_description,whatsapp_number:settings.whatsapp_number,default_theme:settings.default_theme,maintenance_enabled:settings.maintenance_enabled,maintenance_title:settings.maintenance_title,maintenance_message:settings.maintenance_message},'?id=eq.true'),'Site settings saved.')}/></>}</section>}
 {tab==='themes'&&<section className="cms-panel"><h2>Theme Management</h2><p>Setiap tema mengubah seluruh interface: background, surface, text, border, accent, buttons, cards, navigation, forms, admin CMS, dan banner.</p><div className="theme-admin-grid">{Object.entries(THEME_LABELS).map(([id,n])=><button className={settings?.default_theme===id?'theme-choice active':'theme-choice'} key={id} onClick={()=>{setSettings({...settings,default_theme:id});try{localStorage.setItem('king-vandyz-theme-v2',id)}catch{};setTimeout(()=>previewTheme(id),0)}}><span className={`theme-preview ${id}`}/><b>{n}</b></button>)}</div>{settings&&<div className="theme-editor"><div className="theme-editor-head"><b>GLOBAL PALETTE</b><span>{settings.default_theme}</span></div><div className="theme-color-grid">{Object.entries(themeDraft[settings.default_theme]||THEME_DEFAULTS[settings.default_theme]).map(([key,val])=><ColorField key={key} label={key.replace(/^./,m=>m.toUpperCase())} value={val} onChange={v=>{const id=settings.default_theme;setThemeDraft(prev=>{const next={...(prev[id]||THEME_DEFAULTS[id]),[key]:v};applyThemeTokens(id,next);try{localStorage.setItem('king-vandyz-theme-v2',id)}catch{};return {...prev,[id]:next}})}}/>)}</div></div>}<SaveButton onClick={()=>save(async()=>{await mutate('site_settings','PATCH',{default_theme:settings.default_theme,theme_config:themeDraft},'?id=eq.true');previewTheme()},'Theme + colors saved.')}/></section>}
 {tab==='analytics'&&<section className="cms-panel"><h2>Analytics</h2><div className="admin-grid"><Stat icon={Users} label="DAILY ACTIVE" value={stats.active_users}/><Stat icon={Activity} label="ONLINE" value={stats.online_users}/><Stat icon={Boxes} label="TOOL USAGE" value={stats.total_tool_uses}/><Stat icon={Wallet} label="CREDITS SOLD" value={stats.credits_sold}/><Stat icon={ShoppingBag} label="COMPLETED" value={stats.completed_orders}/><Stat icon={Infinity} label="VIP DAYS SOLD" value={stats.vip_sold}/></div></section>}
 {tab==='logs'&&<section className="cms-panel"><h2>Activity Log</h2><div className="log-list">{logs.map(x=><div key={x.id}><Activity size={15}/><b>{x.action}</b><span>{x.admin_username} · {new Date(x.created_at).toLocaleString('id-ID')}</span></div>)}</div></section>}
 </main></div></div>
}
